config/routes.rb
Rails.application.routes.draw do
    get"tasks" => "tasks#index"
    get"tasks/new" => "tasks#new"
    get"tasks/edit" => "tasks#edit"
    
    resources:tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    validates :start_date, presence: true
    validate :end_after_today
      def end_after_today
          if end_date.present? && end_date < Date.today
            errors.add(:end_date, "は今日以降の日付で選択してください")
          end
      end
    validates :end_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end
    
    def new
        @task = Task.new
    end
    
    def create
        @task = Task.new(params.require(:task).permit(:title, :start_date, :end_date, :allday, :memo))
        if @task.save
            flash[:notice] = "スケジュールを登録しました"
            redirect_to :tasks
        else
            render "new"
        end
    end
    
    def show
        @task = Task.find(params[:id])
    end
    
    def edit
        @task = Task.find(params[:id])
    end
    
    def update
        @task = Task.find(params[:id])
        if @task.update(params.require(:task).permit(:title, :start_date, :end_date, :allday, :memo))
            flash[:notice] = "スケジュールを更新しました"
            redirect_to :tasks
        else
            render "edit"
        end
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        flash[:alert] = "スケジュールを削除しました"
        redirect_to :tasks
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
    <footer>
      <h1>現在の日時：<%= Date.current.strftime('%Y年%m月%d日')%><%= content_for?(:count_schedule) ? yield(:count_schedule) : "" %></h1>
    </footer>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
 <% obj.errors.full_messages.each do |message| %>
  <ul>
      <li><%= message %></li>
  </ul>
 <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h2>スケジュール編集</h2>

<%= form_with model: @task do |f| %>
  <table>
      <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title %></td>
      </tr>
      
      <tr>
          <th><%= f.label :start_date ,"開始日" %></th>
          <td><%= f.date_field :start_date %></td>
      </tr>
      
      <tr>
          <th><%= f.label :end_date ,"終了日" %></th>
          <td><%= f.date_field :end_date %></td>
      </tr>
      
      <tr>
          <th><%= f.label :allday ,"終日" %></th>
          <td><%= f.check_box :allday ,{}, "true", "false" %> <br>終日の場合はチェックを入れます</td>
      </tr>
      
      <tr>
          <th><%= f.label :memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :memo %></td>
      </tr>
  </table>
  
  <div>
      <ul>
          <li><%= f.submit "スケジュールの編集を完了する" %></li>
          <li><%= link_to "スケジュール一覧に戻る" ,tasks_path %></li>
      </ul>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h2>スケジュール一覧</h2>

<% if flash[:notice] %>
 <p class="notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
 <p class="alert"><%= flash[:alert] %></p>
<% end %>

<% content_for :count_schedule do %>
    スケジュール合計: <%= Task.count %>
<% end %>

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>スケジュール更新日時</th>
            <th>確認</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    
    <tbody>
        <% @tasks.each do |task| %>
          <tr>
              <td><%= task.id %></td>
              <td><%= task.title %></td>
              <td><%= task.start_date.strftime("%Y年%m月%d日")  %></td>
              <td><%= task.end_date.strftime("%Y年%m月%d日")  %></td>
              <td><% if task.allday == true %>
                   ◯
                  <% else task.allday == false %>
                  
                  <% end %>
              </td>
              <td><%= task.updated_at.to_s(:datetime_jp) %></td>
              <td>
                  <%= link_to"参照",task %>
              </td>
              <td>
                  <%= link_to"編集", [:edit, task] %>
              </td>
              <td>
                  <%= link_to"削除", task, method: :delete, data: { confirm: "本当に削除しますか？" } %>
              </td>
              
          </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "スケジュール新規登録",new_task_path %></p>

app/views/tasks/new.html.erb
<h2>スケジュール新規作成</h2>

<%= render"shared/error",obj: @task %>

<%= form_with model: @task do |f| %>
  <table>
      <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title %></td>
      </tr>
      
      <tr>
          <th><%= f.label :start_date ,"開始日" %></th>
          <td><%= f.date_field :start_date %></td>
      </tr>
      
      <tr>
          <th><%= f.label :end_date ,"終了日" %></th>
          <td><%= f.date_field :end_date %></td>
      </tr>
      
      <tr>
          <th><%= f.label :allday ,"終日" %></th>
          <td><%= f.check_box :allday ,{}, "true", "false" %> <br>終日の場合はチェックを入れます</td>
      </tr>
      
      <tr>
          <th><%= f.label :memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :memo %></td>
      </tr>
  </table>
  
  <div>
      <ul>
          <li><%= f.submit "スケジュールを新規登録する" %></li>
          <li><%= link_to "スケジュール一覧に戻る" ,tasks_path %></li>
      </ul>
  </div>
<% end %>

app/views/tasks/show.html.erb
<h3>スケジュール詳細</h3>

<table>
    <tr>
        <th>タイトル</th>
        <td><%= @task.title %></td>
    </tr>
    <tr>
        <th>開始日</th>
        <td><%= @task.start_date %></td>
    </tr>
    <tr>
        <th>終了日</th>
        <td><%= @task.end_date %></td>
    </tr>
    <tr>
        <th>終日</th>
        <td><% if @task.allday == true %>
               ◯
          <% else @task.allday == false %>
                  
          <% end %>
        </td>
    </tr>
    <tr>
        <th>スケジュールメモ</th>
        <td><%= @task.memo %></td>
    </tr>
</table>

<div>
    <ul>
        <li><%= link_to"スケジュール一覧に戻る",tasks_path %></li>
        <li><%= link_to"スケジュールを編集する", edit_task_path %></li>
        <li><%= link_to"スケジュールを削除", task_path, method: :delete, data: { confirm: "本当に削除しますか？" } %></li>
    </ul>
</div>